
DROP TABLE IF EXISTS rapidapi_cache;
CREATE TABLE rapidapi_cache (
  id TEXT PRIMARY KEY,
  slug TEXT,
  category TEXT,
  categorySlug TEXT,
  brand TEXT,
  title TEXT,
  description TEXT,
  basePrice REAL,
  retailPrice REAL,
  stockStatus TEXT,
  image_url TEXT,
  images_json TEXT DEFAULT NULL,
  features_json TEXT DEFAULT NULL
);

INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B00HUIWK1W', 'soto-compact-helix-coffee-maker-portable-stainless-stee', 'Pour-Over Coffee', 'pour-over-coffee', 'AeroBrew', 'SOTO Compact Helix Coffee Maker', 'AeroBrew pour-over coffee — authentic quality, carefully selected for everyday use.', 22.99, 28.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61Rh71PQYRL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0821DTMGT', 'cosori-pour-over-coffee-maker-with-double-layer-stainle', 'Pour-Over Coffee', 'pour-over-coffee', 'AeroBrew', 'COSORI Pour Over Coffee Maker with Double Layer Stainless Steel F…', 'AeroBrew pour-over coffee — authentic quality, carefully selected for everyday use.', 29.49, 36.86, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71ZDozIDtcL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DVSKB76B', 'pour-over-coffee-dripper-triple-layer-stainless-steel-c', 'Pour-Over Coffee', 'pour-over-coffee', 'AeroBrew', 'Pour over Coffee Dripper', 'AeroBrew pour-over coffee — authentic quality, carefully selected for everyday use.', 20.99, 26.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81ZWrEuWMGL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FNRN2SYH', 'reusable-4-coffee-filter-for-technivorm-moccamaster-kbg', 'Pour-Over Coffee', 'pour-over-coffee', 'AeroBrew', 'Reusable #4 Coffee Filter for Technivorm Moccamaster KBGV and KBT…', 'AeroBrew pour-over coffee — authentic quality, carefully selected for everyday use.', 27.97, 34.96, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81JSSbMvaxL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B01DOANRP2', 'nrp-taller-4-gold-tone-permanent-coffee-filter-compatib', 'Pour-Over Coffee', 'pour-over-coffee', 'AeroBrew', 'NRP Taller #4 Gold', 'AeroBrew pour-over coffee — authentic quality, carefully selected for everyday use.', 10.6, 13.25, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61+4fRHPtJL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08HCJ2LD7', 'delibru-reusable-keurig-k-duo-coffee-filter-8-12-cups-g', 'Pour-Over Coffee', 'pour-over-coffee', 'AeroBrew', 'Delibru Reusable Keurig K', 'AeroBrew pour-over coffee — authentic quality, carefully selected for everyday use.', 7.99, 9.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61npBbWFlsL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07DJ53GZQ', 'spring-chef-stainless-steel-magnetic-measuring-spoons-s', 'Kitchen Tools', 'kitchen-tools', 'ChefCore', 'Spring Chef Stainless Steel Magnetic Measuring Spoons Set with St…', 'ChefCore kitchen tools — authentic quality, carefully selected for everyday use.', 9.99, 12.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71pTVVH3VrL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0BGPC4YFW', 'magnetic-measuring-spoons-set-of-9-dual-sided-stainless', 'Kitchen Tools', 'kitchen-tools', 'ChefCore', 'Magnetic Measuring Spoons Set of 9 Dual Sided Stainless Steel Mea…', 'ChefCore kitchen tools — authentic quality, carefully selected for everyday use.', 14.97, 18.71, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71bYSR1iY3L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08MVSN321', 'smithcraft-measuring-cups-and-spoons-set-14-copper-meas', 'Kitchen Tools', 'kitchen-tools', 'ChefCore', 'Smithcraft Measuring Cups and Spoons Set 14', 'ChefCore kitchen tools — authentic quality, carefully selected for everyday use.', 45.97, 57.46, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81WcZAOyu9L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CXF817YW', 'eletronova-safe-mandoline-slicer-for-kitchen-vegetable-', 'Kitchen Tools', 'kitchen-tools', 'ChefCore', 'Eletronova Safe Mandoline Slicer for Kitchen', 'ChefCore kitchen tools — authentic quality, carefully selected for everyday use.', 29.99, 37.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61ZB7xDLFxL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B000LCP6EW', 'benriner-japanese-mandolin-vegetable-slicer', 'Kitchen Tools', 'kitchen-tools', 'ChefCore', 'Benriner Japanese Mandolin Vegetable Slicer', 'ChefCore kitchen tools — authentic quality, carefully selected for everyday use.', 29.97, 39.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71WEscyzClL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B000BI8EDG', 'benriner-japanese-vegetable-slicer-old-version', 'Kitchen Tools', 'kitchen-tools', 'ChefCore', 'Benriner Japanese Vegetable Slicer', 'ChefCore kitchen tools — authentic quality, carefully selected for everyday use.', 29.07, 36.34, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61VWjwetlBL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CV6J1KWD', 'itzy-ritzy-itzy-ritzy-packing-cubes-for-travel-set-of-3', 'Home Organization', 'home-organization', 'TidySpace', 'Itzy Ritzy Itzy Ritzy Packing Cubes for Travel – Set of 3 Packing…', 'TidySpace home organization — authentic quality, carefully selected for everyday use.', 24.49, 30.61, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61XSM8jJd0L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0B9YPVGN2', 'nordace-nordace-travel-packing-organizers-set-for-men-a', 'Home Organization', 'home-organization', 'TidySpace', 'Nordace Nordace Travel Packing Organizers Set for Men and Women', 'TidySpace home organization — authentic quality, carefully selected for everyday use.', 69.99, 87.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71xUYRPuPXL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0B5B8T6P3', 'itzy-ritzy-itzy-ritzy-packing-cubes-for-travel-set-of-3', 'Home Organization', 'home-organization', 'TidySpace', 'Itzy Ritzy Itzy Ritzy Packing Cubes for Travel – Set of 3 Large P…', 'TidySpace home organization — authentic quality, carefully selected for everyday use.', 31.35, 39.19, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61DMo4rbeKL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B097P34VB9', 'youeon-set-of-6-bamboo-drawer-organizer-storage-box-adj', 'Home Organization', 'home-organization', 'TidySpace', 'Youeon Set of 6 Bamboo Drawer Organizer Storage Box', 'TidySpace home organization — authentic quality, carefully selected for everyday use.', 23.99, 29.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71ZbayiVa9L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CRHGPJ4T', 'spaceaid-bamboo-4-pack-dresser-drawer-dividers-4-65-hig', 'Home Organization', 'home-organization', 'TidySpace', 'SpaceAid Bamboo 4 Pack Dresser Drawer Dividers', 'TidySpace home organization — authentic quality, carefully selected for everyday use.', 28.98, 36.23, 'IN_STOCK', 'https://m.media-amazon.com/images/I/710WKojCfLL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08BFHBR6M', 'bameos-drawer-dividers-kitchen-organization-bamboo-uten', 'Home Organization', 'home-organization', 'TidySpace', 'BAMEOS Drawer Dividers kitchen Organization Bamboo Utensil Organi…', 'TidySpace home organization — authentic quality, carefully selected for everyday use.', 22.46, 24.96, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71XQCpeiLeL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FF1SS9VD', 'new-silicone-shower-scrubber-with-straps-360-anti-slip-', 'Bath & Shower', 'bath-shower', 'Zenith Bath', 'New Silicone Shower Scrubber with Straps', 'Zenith Bath bath & shower — authentic quality, carefully selected for everyday use.', 8.99, 11.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71LqnQXH55L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CL178273', 'blackwood-for-men-double-duty-beard-amp-body-scrubber-d', 'Bath & Shower', 'bath-shower', 'Zenith Bath', 'Blackwood For Men Double Duty Beard &amp; Body Scrubber', 'Zenith Bath bath & shower — authentic quality, carefully selected for everyday use.', 19.99, 24.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71bqviFsfQL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08HKWTMNR', 'upgrade-2-in-1-bath-and-shampoo-body-brush-silicone-exf', 'Bath & Shower', 'bath-shower', 'Zenith Bath', 'Upgrade 2 in 1 Bath and Shampoo Body Brush', 'Zenith Bath bath & shower — authentic quality, carefully selected for everyday use.', 6.99, 8.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61CExKuoTML._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0F21KWTNN', 'foldable-bathtub-caddy-tray-for-tub-bamboo-expandable-b', 'Bath & Shower', 'bath-shower', 'Zenith Bath', 'Foldable Bathtub Caddy Tray for Tub', 'Zenith Bath bath & shower — authentic quality, carefully selected for everyday use.', 21.98, 29.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71NMQD8ANcL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DJDQ7P4C', 'royal-craft-wood-premium-foldable-bathtub-tray-caddy-wo', 'Bath & Shower', 'bath-shower', 'Zenith Bath', 'ROYAL CRAFT WOOD Premium Foldable Bathtub Tray Caddy', 'Zenith Bath bath & shower — authentic quality, carefully selected for everyday use.', 29.97, 39.97, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81DSmTYTWPL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0109CZDFU', 'bathtub-tray-for-tub-natural-bamboo-bath-tray-expandabl', 'Bath & Shower', 'bath-shower', 'Zenith Bath', 'Bathtub Tray for Tub', 'Zenith Bath bath & shower — authentic quality, carefully selected for everyday use.', 29.99, 34.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71uC3w3PwiL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B088396TM2', 'resistance-bands-for-working-out-with-workout-bands-gui', 'Fitness Accessories', 'fitness-accessories', 'CoreFit', 'Resistance Bands for Working Out with Workout Bands Guide. 4 Boot…', 'CoreFit fitness accessories — authentic quality, carefully selected for everyday use.', 21.99, 27.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/91UnDO-XhlL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07D7KX9PX', 'arena-strength-fabric-booty-bands-fabric-exercise-bands', 'Fitness Accessories', 'fitness-accessories', 'CoreFit', 'Arena Strength Fabric Booty Bands', 'CoreFit fitness accessories — authentic quality, carefully selected for everyday use.', 29, 36.25, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81t4HW9AZ5L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0C6SV2KDC', 'fabric-resistance-bands-for-working-out-5-levels-booty-', 'Fitness Accessories', 'fitness-accessories', 'CoreFit', 'Fabric Resistance Bands for Working Out', 'CoreFit fitness accessories — authentic quality, carefully selected for everyday use.', 16.95, 21.19, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81f6nR2TG6L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B072FTZ734', 'house-of-jack-co-duck-slim-money-clip-wallet-for-men-fr', 'Everyday Carry', 'everyday-carry', 'Apex Minimal', 'House of Jack Co. Duck Slim Money Clip Wallet for Men', 'Apex Minimal everyday carry — authentic quality, carefully selected for everyday use.', 29.99, 35, 'IN_STOCK', 'https://m.media-amazon.com/images/I/91Ezwy1g8hL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B093WW7ZKC', 'couro50-front-pocket-minimalist-leather-slim-wallet-rfi', 'Everyday Carry', 'everyday-carry', 'Apex Minimal', 'Couro50 Front Pocket Minimalist Leather Slim Wallet RFID Blocking…', 'Apex Minimal everyday carry — authentic quality, carefully selected for everyday use.', 24.9, 31.13, 'IN_STOCK', 'https://m.media-amazon.com/images/I/716oCyVXKlL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08KSVGBRM', 'rugged-gifts-ruggedgifts-personalized-magnetic-money-cl', 'Everyday Carry', 'everyday-carry', 'Apex Minimal', 'Rugged Gifts RUGGEDGIFTS Personalized Magnetic Money Clip', 'Apex Minimal everyday carry — authentic quality, carefully selected for everyday use.', 34.99, 43.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81oLZ84kORL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CNF9YVCZ', 'the-ridge-wallet-for-men-slim-minimalist-compact-wallet', 'Everyday Carry', 'everyday-carry', 'Apex Minimal', 'The Ridge Wallet for Men', 'Apex Minimal everyday carry — authentic quality, carefully selected for everyday use.', 149.99, 187.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/91NmHCh0Z0L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B01MG9AL2E', 'the-ridge-ridge-wallet-for-men-slim-minimalist-compact-', 'Everyday Carry', 'everyday-carry', 'Apex Minimal', 'The Ridge Ridge Wallet for Men', 'Apex Minimal everyday carry — authentic quality, carefully selected for everyday use.', 149.99, 187.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61Ayuf6u91L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0GHPQ9J2Y', 'mopani-compact-titanium-wallet-amp-money-clip-premium-c', 'Everyday Carry', 'everyday-carry', 'Apex Minimal', 'MOPANI Compact Titanium Wallet &amp; Money Clip – Premium Credit …', 'Apex Minimal everyday carry — authentic quality, carefully selected for everyday use.', 19.69, 24.61, 'IN_STOCK', 'https://m.media-amazon.com/images/I/41dtHexvSKL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DQJ6JZY6', 'xmlinper-passport-holder-and-card-slot-combo-rfid-block', 'Travel Accessories', 'travel-accessories', 'AeroTravel', 'XMLINPER Passport Holder and Card Slot Combo RFID Blocking Leathe…', 'AeroTravel travel accessories — authentic quality, carefully selected for everyday use.', 6.99, 8.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81THW++RPqL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07LG3TYJS', 'pascacoo-passport-holder-cover-wallet-rfid-blocking-lea', 'Travel Accessories', 'travel-accessories', 'AeroTravel', 'PASCACOO Passport Holder Cover Wallet RFID Blocking Leather Card …', 'AeroTravel travel accessories — authentic quality, carefully selected for everyday use.', 9.99, 12.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71Q-LB5K-tL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FCS1DXDG', 'rhottbiy-passport-holder-for-travel-rfid-blocking-passp', 'Travel Accessories', 'travel-accessories', 'AeroTravel', 'RHOttbiy Passport Holder for Travel', 'AeroTravel travel accessories — authentic quality, carefully selected for everyday use.', 8.99, 11.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/91j9dfYToUL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0C3Q899C6', 'choieo-embroidered-luggage-tag-initial-bag-tag-for-suit', 'Travel Accessories', 'travel-accessories', 'AeroTravel', 'CHOIEO Embroidered Luggage Tag – Initial Bag Tag for Suitcase', 'AeroTravel travel accessories — authentic quality, carefully selected for everyday use.', 6.99, 8.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61eleEBN9WL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FDRC8RPP', 'sumlliay-2pack-luggage-tags-for-suitcases-cute-unique-p', 'Travel Accessories', 'travel-accessories', 'AeroTravel', 'Sumlliay 2Pack Luggage Tags for Suitcases', 'AeroTravel travel accessories — authentic quality, carefully selected for everyday use.', 7.21, 9.01, 'IN_STOCK', 'https://m.media-amazon.com/images/I/719W3aC5UQL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B09YTKSCJW', 'ubouigr-custom-personalized-leather-travel-luggage-tag-', 'Travel Accessories', 'travel-accessories', 'AeroTravel', 'Ubouigr Custom Personalized Leather Travel Luggage Tag Luggage Id…', 'AeroTravel travel accessories — authentic quality, carefully selected for everyday use.', 13.99, 17.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81PiDZRhl3L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B01F6N03XO', 'max-and-neo-reflective-nylon-dog-leash-we-donate-a-leas', 'Pet Accessories', 'pet-accessories', 'Paws & Trek', 'Max and Neo Reflective Nylon Dog Leash', 'Paws & Trek pet accessories — authentic quality, carefully selected for everyday use.', 16.99, 21.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71tFLPh6u3L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07D4B4L24', 'plutus-pet-double-handle-dog-leash-6ft-padded-heavy-dut', 'Pet Accessories', 'pet-accessories', 'Paws & Trek', 'Plutus Pet Double Handle Dog Leash', 'Paws & Trek pet accessories — authentic quality, carefully selected for everyday use.', 13.45, 16.81, 'IN_STOCK', 'https://m.media-amazon.com/images/I/51+K5OCB92L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B09W65K38F', 'leash-boss-6ft-ultra-comfort-double-thick-soft-padded-h', 'Pet Accessories', 'pet-accessories', 'Paws & Trek', 'Leash Boss 6ft Ultra Comfort Double', 'Paws & Trek pet accessories — authentic quality, carefully selected for everyday use.', 19.95, 24.94, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71Nb6X4Kb1L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08CTVFN15', 'dog-travel-bag-by-modoker-dog-travel-kit-for-a-weekend-', 'Pet Accessories', 'pet-accessories', 'Paws & Trek', 'Dog Travel Bag by Modoker', 'Paws & Trek pet accessories — authentic quality, carefully selected for everyday use.', 44.99, 56.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81EXyg8CSDL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CMXF176P', 'aonkey-collapsible-dog-bowls-with-bottle-carrier-2-pack', 'Pet Accessories', 'pet-accessories', 'Paws & Trek', 'Aonkey Collapsible Dog Bowls with Bottle Carrier', 'Paws & Trek pet accessories — authentic quality, carefully selected for everyday use.', 5.39, 5.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61jSluAyC5L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07MDGSVB2', 'teamoy-double-layer-dog-travel-bag-dog-bag-for-supplies', 'Pet Accessories', 'pet-accessories', 'Paws & Trek', 'Teamoy Double Layer Dog Travel Bag', 'Paws & Trek pet accessories — authentic quality, carefully selected for everyday use.', 28.99, 36.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71Bd8zLhSwL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08BCSVP3H', 'ippinka-sustee-aquameter-bundle-of-12-house-plant-soil-', 'Plant Care', 'plant-care', 'Verdant Supply', 'IPPINKA Sustee Aquameter', 'Verdant Supply plant care — authentic quality, carefully selected for everyday use.', 62.95, 78.69, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71AJcBzHAyL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0G1352LMY', 'hslgove-soil-test-kit-2-in-1-soil-moisture-meter-soil-p', 'Plant Care', 'plant-care', 'Verdant Supply', 'HSLGOVE Soil Test Kit', 'Verdant Supply plant care — authentic quality, carefully selected for everyday use.', 15.99, 19.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71l5wRwxt4L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FSRGYJZN', 'soil-moisture-meter-plant-water-monitor-hygrometer-sens', 'Plant Care', 'plant-care', 'Verdant Supply', 'Soil Moisture Meter', 'Verdant Supply plant care — authentic quality, carefully selected for everyday use.', 25.99, 32.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71Qk8e2sR4L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0F6TMXM1N', '16-oz-plant-watering-globes-for-indoor-plants-with-terr', 'Plant Care', 'plant-care', 'Verdant Supply', '16 Oz Plant Watering Globes for Indoor Plants with Terracotta Sel…', 'Verdant Supply plant care — authentic quality, carefully selected for everyday use.', 18.95, 23.69, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71GY0X8tKBL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FHJGYFB3', 'terracotta-self-watering-planter-insert-set-of-4-clay-o', 'Plant Care', 'plant-care', 'Verdant Supply', 'Terracotta Self Watering Planter Insert', 'Verdant Supply plant care — authentic quality, carefully selected for everyday use.', 40.95, 51.19, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81XmCxqDBBL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0G1LVFNTC', 'soilagua-16-oz-drip-irrigation-stakes-large-plant-water', 'Plant Care', 'plant-care', 'Verdant Supply', 'Soilagua 16 oz Drip Irrigation Stakes', 'Verdant Supply plant care — authentic quality, carefully selected for everyday use.', 44.99, 56.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71yWqnl2S3L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DLX4S6X7', 'kaf-home-haven-kitchen-tea-towel-set-of-2-quick-drying-', 'Cleaning & Laundry', 'cleaning-laundry', 'CleanSet', 'KAF Home Haven Kitchen Tea Towel', 'CleanSet cleaning & laundry — authentic quality, carefully selected for everyday use.', 9.99, 19.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71L+GubghqL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CGC1DJZF', 'geometry-kitchen-tea-towels-quick-dry-microfiber-dish-t', 'Cleaning & Laundry', 'cleaning-laundry', 'CleanSet', 'GEOMETRY Kitchen Tea Towels', 'CleanSet cleaning & laundry — authentic quality, carefully selected for everyday use.', 32, 40, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81NZcCdIi0L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FRFT2PYH', 'geometry-christmas-kitchen-towels-quick-dry-microfiber-', 'Cleaning & Laundry', 'cleaning-laundry', 'CleanSet', 'GEOMETRY Christmas Kitchen Towels', 'CleanSet cleaning & laundry — authentic quality, carefully selected for everyday use.', 45, 56.25, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81BAZFlL5GL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FF4515N3', '15pcs-crevice-cleaning-brush-hard-bristle-scrub-brushes', 'Cleaning & Laundry', 'cleaning-laundry', 'CleanSet', '15pcs Crevice Cleaning Brush', 'CleanSet cleaning & laundry — authentic quality, carefully selected for everyday use.', 5.39, 5.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71D4xkfV8wL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DT1KCBPL', 'electric-spin-scrubber-bathroom-cleaner-brush-with-full', 'Cleaning & Laundry', 'cleaning-laundry', 'CleanSet', 'Electric Spin Scrubber', 'CleanSet cleaning & laundry — authentic quality, carefully selected for everyday use.', 30.44, 34.44, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61jAHdQoXgL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0G9JXNJS8', '9pcs-crevice-cleaning-brush-hard-bristle-scrub-brushes-', 'Cleaning & Laundry', 'cleaning-laundry', 'CleanSet', '9PCS Crevice Cleaning Brush', 'CleanSet cleaning & laundry — authentic quality, carefully selected for everyday use.', 5.99, 9.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71uwYDWatbL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CR4TVSFX', 'nuby-teethe-n-x27-pop-sensory-play-teether-baby-teethin', 'Baby Accessories', 'baby-accessories', 'TinyNest', 'Nuby Teethe N&#x27; Pop Sensory Play Teether', 'TinyNest baby accessories — authentic quality, carefully selected for everyday use.', 7.99, 9.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71GB3oa6SnL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FFMLGGKH', 'haakaa-silicone-baby-teether-toys-nipple-shaped-end-for', 'Baby Accessories', 'baby-accessories', 'TinyNest', 'haakaa Silicone Baby Teether Toys', 'TinyNest baby accessories — authentic quality, carefully selected for everyday use.', 9.99, 12.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61ZQSnAv2qL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0G3WGHFB4', 'easter-teething-toys-for-newborns-0-3-6months-food-grad', 'Baby Accessories', 'baby-accessories', 'TinyNest', 'Easter Teething Toys for Newborns 0', 'TinyNest baby accessories — authentic quality, carefully selected for everyday use.', 6.99, 9.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71gWP-RAFQL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B01M7SCDDA', 'babymoov-baby-food-jars-set-of-6-8oz-each-storage-conta', 'Baby Accessories', 'baby-accessories', 'TinyNest', 'Babymoov Baby Food Jars', 'TinyNest baby accessories — authentic quality, carefully selected for everyday use.', 13.99, 17.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61ZZENT7UfL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07XYM45ZQ', 'skip-hop-baby-formula-container-formula-to-food', 'Baby Accessories', 'baby-accessories', 'TinyNest', 'Skip Hop Baby Formula Container', 'TinyNest baby accessories — authentic quality, carefully selected for everyday use.', 9.79, 12.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/51-pVieA72L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B09H5LH7RH', 'haakaa-silicone-nibble-freezer-tray-breastmilk-teething', 'Baby Accessories', 'baby-accessories', 'TinyNest', 'Haakaa Silicone Nibble Freezer Tray', 'TinyNest baby accessories — authentic quality, carefully selected for everyday use.', 18.99, 23.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71jbd7IfXgL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CZ6T84CG', 'bituemly-beard-brush-natural-boar-bristles-beard-brush-', 'Men''s Grooming', 'mens-grooming', 'Groom & Go', 'Bituemly Beard Brush', 'Groom & Go men''s grooming — authentic quality, carefully selected for everyday use.', 8.47, 9.97, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81iN8UmXlrL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B01NCDXUEQ', 'zeus-sandalwood-beard-comb-for-men-natural-wooden-comb-', 'Men''s Grooming', 'mens-grooming', 'Groom & Go', 'ZEUS Sandalwood Beard Comb for Men', 'Groom & Go men''s grooming — authentic quality, carefully selected for everyday use.', 19.95, 24.94, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61AeRkL5lML._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FVSMCKYY', '3pcs-beard-brush-comb-set-for-men-black-walnut-wood-dua', 'Men''s Grooming', 'mens-grooming', 'Groom & Go', '3PCS Beard Brush Comb Set for Men', 'Groom & Go men''s grooming — authentic quality, carefully selected for everyday use.', 13.99, 16.19, 'IN_STOCK', 'https://m.media-amazon.com/images/I/91idQGLd-QL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08C7P8TWQ', 'bfwood-boar-bristle-beard-brush-black-wood-walnut-milit', 'Men''s Grooming', 'mens-grooming', 'Groom & Go', 'BFWood Boar Bristle Beard Brush', 'Groom & Go men''s grooming — authentic quality, carefully selected for everyday use.', 14.39, 15.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/813cIIPr2uL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07145HVFP', 'seven-potions-beard-brush-for-men-with-100-first-cut-bo', 'Men''s Grooming', 'mens-grooming', 'Groom & Go', 'Seven Potions Beard Brush For Men With 100% First Cut Boar Bristl…', 'Groom & Go men''s grooming — authentic quality, carefully selected for everyday use.', 21.99, 27.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61f8hwsEvxL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FQJDN999', 'waterproof-beach-blanket-picnic-outdoor-camping-mat-ove', 'Outdoor & Picnic', 'outdoor-picnic', 'OutKraft', 'Waterproof Beach Blanket Picnic Outdoor Camping Mat Oversized Ext…', 'OutKraft outdoor & picnic — authentic quality, carefully selected for everyday use.', 26.99, 33.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81N8XsE-Y4L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0F6CTSCDY', 'outdoor-picnic-blanket-portable-ultrasonic-waterproof-p', 'Outdoor & Picnic', 'outdoor-picnic', 'OutKraft', 'Outdoor Picnic Blanket Portable Ultrasonic Waterproof Picnic Geom…', 'OutKraft outdoor & picnic — authentic quality, carefully selected for everyday use.', 25.99, 32.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81inY746PBL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07SWWTXVV', 'extra-large-picnic-blanket-80-quot-x60-quot-waterproof-', 'Outdoor & Picnic', 'outdoor-picnic', 'OutKraft', 'Extra Large Picnic Blanket', 'OutKraft outdoor & picnic — authentic quality, carefully selected for everyday use.', 22.99, 29.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71lfuB9kT7L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B00FKCRZME', 'to-go-ware-kid-x27-s-bamboo-utensil-set-melon-pink-1-ea', 'Outdoor & Picnic', 'outdoor-picnic', 'OutKraft', 'TO GO WARE Kid&#x27;s Bamboo Utensil Set Melon Pink', 'OutKraft outdoor & picnic — authentic quality, carefully selected for everyday use.', 11.5, 14.38, 'IN_STOCK', 'https://m.media-amazon.com/images/I/91a8nxJrs4L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B00AY8TZ3Q', 'to-go-ware-to-go-ware-reusable-bamboo-travel-utensils-w', 'Outdoor & Picnic', 'outdoor-picnic', 'OutKraft', 'To Go Ware To Go Ware Reusable Bamboo Travel Utensils with Carryi…', 'OutKraft outdoor & picnic — authentic quality, carefully selected for everyday use.', 15.19, 18.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61AJHX48oKL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0867S4DLF', 'uptrust-2-set-bamboo-cutlery-set-bamboo-travel-utensil-', 'Outdoor & Picnic', 'outdoor-picnic', 'OutKraft', 'UPTRUST 2 Set Bamboo Cutlery Set Bamboo Travel Utensil Reusable T…', 'OutKraft outdoor & picnic — authentic quality, carefully selected for everyday use.', 11.99, 14.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/717koAAN3UL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0G1MFX695', 'betife-pill-organizer-2-times-a-day-am-pm-weekly-7-day-', 'Wellness Accessories', 'wellness-accessories', 'PureHabit', 'Betife Pill Organizer 2 Times a Day', 'PureHabit wellness accessories — authentic quality, carefully selected for everyday use.', 18.99, 22.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61O6Yb5+XmL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0D25Q83D1', 'large-monthly-pill-organizer-28-day-case-organizerd-ext', 'Wellness Accessories', 'wellness-accessories', 'PureHabit', 'Large Monthly Pill Organizer 28 Day Case Organizerd Extra Large C…', 'PureHabit wellness accessories — authentic quality, carefully selected for everyday use.', 16.99, 21.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71D+-WZn64L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0BQJ2XZWF', 'auvon-xl-weekly-pill-organizer-2-times-a-day-pill-box-7', 'Wellness Accessories', 'wellness-accessories', 'PureHabit', 'AUVON XL Weekly Pill Organizer 2 Times a Day', 'PureHabit wellness accessories — authentic quality, carefully selected for everyday use.', 6.99, 9.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71ujE1fyeaL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07H2GM46Y', 'auvon-pill-box-2-times-a-day-weekly-pill-organizer-am-p', 'Wellness Accessories', 'wellness-accessories', 'PureHabit', 'AUVON Pill Box 2 Times a Day', 'PureHabit wellness accessories — authentic quality, carefully selected for everyday use.', 6.97, 9.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71GWdq3OV2L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FMXY9FKM', 'auvon-xl-weekly-pill-organizer-2-times-a-day-pill-box-7', 'Wellness Accessories', 'wellness-accessories', 'PureHabit', 'AUVON XL Weekly Pill Organizer 2 Times a Day', 'PureHabit wellness accessories — authentic quality, carefully selected for everyday use.', 9.99, 12.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71Ltist5N0L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B098DF9Q4Z', 'sukuos-large-weekly-pill-organizer-2-times-a-day-daily-', 'Wellness Accessories', 'wellness-accessories', 'PureHabit', 'Sukuos Large Weekly Pill Organizer 2 Times a Day', 'PureHabit wellness accessories — authentic quality, carefully selected for everyday use.', 9.99, 12.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61BqdM7clKL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B09YSVR5GF', 'itsy-belle-studio-floral-wedding-wrapping-paper-sheets-', 'Party & Gifting', 'party-gifting', 'WrapRight', 'Itsy Belle Studio Floral Wedding Wrapping Paper sheets + Ribbon S…', 'WrapRight party & gifting — authentic quality, carefully selected for everyday use.', 14.99, 18.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/717FyysCAjL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CSM2W3W9', 'sikiweiter-hamburger-wrapping-paper-burger-wrapping-pap', 'Party & Gifting', 'party-gifting', 'WrapRight', 'Sikiweiter Hamburger Wrapping Paper', 'WrapRight party & gifting — authentic quality, carefully selected for everyday use.', 9.99, 12.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/711DU48BIOL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CHRR1MX7', 'ruspepa-birthday-wrapping-paper-sheets-with-13-year-old', 'Party & Gifting', 'party-gifting', 'WrapRight', 'RUSPEPA Birthday Wrapping Paper Sheets with 13 Year Old Pink Patt…', 'WrapRight party & gifting — authentic quality, carefully selected for everyday use.', 8.91, 9.9, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81SBaz7C31L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DSVK8H5X', '24-pcs-pink-bows-for-gift-wrapping-4-quot-pre-tied-twis', 'Party & Gifting', 'party-gifting', 'WrapRight', '24 PCS Pink Bows for Gift Wrapping 4&quot; Pre', 'WrapRight party & gifting — authentic quality, carefully selected for everyday use.', 14.99, 18.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81s+RwzkGXL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DR2KHCFJ', 'daifunli-60-pcs-coquette-bow-pink-bow-birthday-party-de', 'Party & Gifting', 'party-gifting', 'WrapRight', 'Daifunli 60 Pcs Coquette Bow', 'WrapRight party & gifting — authentic quality, carefully selected for everyday use.', 8.63, 9.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71nbxECsNhL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07XFGQMW5', 'light-up-glowing-gift-bows-6-iridescent-led-ribbon-bow-', 'Party & Gifting', 'party-gifting', 'WrapRight', 'Light Up Glowing Gift Bows', 'WrapRight party & gifting — authentic quality, carefully selected for everyday use.', 12.95, 16.19, 'IN_STOCK', 'https://m.media-amazon.com/images/I/713Pvt+jB8L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FDB2J2FB', 'brown-gift-boxes-with-ribbon-4x4x4-quot-foldable-paper-', 'Gift Boxes & Packaging', 'gift-boxes-packaging', 'BoxCraft', 'Brown Gift Boxes with Ribbon – 4x4x4&quot; Foldable Paper Boxes w…', 'BoxCraft gift boxes & packaging — authentic quality, carefully selected for everyday use.', 8.99, 11.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61+wGkb2Z0L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0D8GL4PLK', 'large-brown-kraft-cookie-boxes-with-ribbons-amp-sticker', 'Gift Boxes & Packaging', 'gift-boxes-packaging', 'BoxCraft', 'Large Brown Kraft Cookie Boxes with Ribbons &amp; Sticker (20 Pac…', 'BoxCraft gift boxes & packaging — authentic quality, carefully selected for everyday use.', 25.99, 32.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/815mb5IidyL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0C557L93X', 'popgiftu-18-pack-kraft-christmas-boxes-with-lids-4-size', 'Gift Boxes & Packaging', 'gift-boxes-packaging', 'BoxCraft', 'POPGIFTU 18', 'BoxCraft gift boxes & packaging — authentic quality, carefully selected for everyday use.', 26.99, 33.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81dkXvkgqRL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FD7HH6RK', '9x9x3-inches-white-shipping-boxes-set-of-25-cardboard-b', 'Gift Boxes & Packaging', 'gift-boxes-packaging', 'BoxCraft', '9x9x3 Inches White Shipping Boxes Set of 25，Cardboard Boxes Recyc…', 'BoxCraft gift boxes & packaging — authentic quality, carefully selected for everyday use.', 29.99, 37.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71uCwkkm2ML._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07864XX8J', 'boxes-fast-shipping-boxes-small-7-quot-l-x-4-quot-w-x-3', 'Gift Boxes & Packaging', 'gift-boxes-packaging', 'BoxCraft', 'Boxes Fast', 'BoxCraft gift boxes & packaging — authentic quality, carefully selected for everyday use.', 35.79, 44.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81Q6tzC8lSL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0BG4S364X', 'rlavbl-9x6x2-shipping-boxes-set-of-50-white-small-corru', 'Gift Boxes & Packaging', 'gift-boxes-packaging', 'BoxCraft', 'RLAVBL 9x6x2 Shipping Boxes Set of 50', 'BoxCraft gift boxes & packaging — authentic quality, carefully selected for everyday use.', 31.99, 39.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61fEkx5KWQL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0722YJB5M', 'kikkerland-kikkerland-palm-reader-jewelry-display-manne', 'Jewellery Accessories', 'jewellery-accessories', 'TrinketsHaven', 'Kikkerland Kikkerland Palm Reader Jewelry Display Mannequin Holde…', 'TrinketsHaven jewellery accessories — authentic quality, carefully selected for everyday use.', 21.3, 25, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71Q3InO5X2L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0CHN18HJT', 'pangkeep-pangkeep-jewelry-holder-stand-2-tier-necklace-', 'Jewellery Accessories', 'jewellery-accessories', 'TrinketsHaven', 'Pangkeep Pangkeep Jewelry Holder Stand', 'TrinketsHaven jewellery accessories — authentic quality, carefully selected for everyday use.', 14.99, 15.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/612KiMaAL5L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0GKNH6469', 'vlando-vlando-2-tier-bracelet-holder-with-tray-leather-', 'Jewellery Accessories', 'jewellery-accessories', 'TrinketsHaven', 'VLANDO Vlando 2 Tier Bracelet Holder with Tray', 'TrinketsHaven jewellery accessories — authentic quality, carefully selected for everyday use.', 19.99, 24.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71gsH-upDNL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0F596DFRL', 'lolalet-lolalet-handmade-ceramic-ring-dish-jewelry-tray', 'Jewellery Accessories', 'jewellery-accessories', 'TrinketsHaven', 'Lolalet Lolalet Handmade Ceramic Ring Dish Jewelry Tray Plate wit…', 'TrinketsHaven jewellery accessories — authentic quality, carefully selected for everyday use.', 9.99, 12.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/716xRmgVCSL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B09RPKGVDW', 'collective-home-collective-home-ceramic-jewelry-tray-de', 'Jewellery Accessories', 'jewellery-accessories', 'TrinketsHaven', 'COLLECTIVE HOME COLLECTIVE HOME', 'TrinketsHaven jewellery accessories — authentic quality, carefully selected for everyday use.', 13.99, 15.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71ZjV0QJZkL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B08BK7GHJ5', 'topthink-topthink-gift-for-mother-of-the-groom-from-bri', 'Jewellery Accessories', 'jewellery-accessories', 'TrinketsHaven', 'Topthink Topthink Gift For Mother of The Groom From Bride', 'TrinketsHaven jewellery accessories — authentic quality, carefully selected for everyday use.', 15.99, 19.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81qphL3nrCL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0F2SSMLD5', 'songmics-strong-magnetic-spice-rack-for-refrigerator-se', 'Spice & Pantry Tools', 'spice-pantry-tools', 'SpiceVault', 'SONGMICS Strong Magnetic Spice Rack for Refrigerator', 'SpiceVault spice & pantry tools — authentic quality, carefully selected for everyday use.', 21.99, 29.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/713jrG+RkCL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FPDZKHFF', 'vanpet-magnetic-spice-rack-for-refrigerator-magnetic-fr', 'Spice & Pantry Tools', 'spice-pantry-tools', 'SpiceVault', 'VANPET Magnetic Spice Rack for Refrigerator', 'SpiceVault spice & pantry tools — authentic quality, carefully selected for everyday use.', 16.99, 21.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71n83--EP8L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0BWYBWRFT', 'huggiegems-2-pack-magnetic-spice-storage-rack-organizer', 'Spice & Pantry Tools', 'spice-pantry-tools', 'SpiceVault', 'HuggieGems 2 Pack Magnetic Spice Storage Rack Organizer for Refri…', 'SpiceVault spice & pantry tools — authentic quality, carefully selected for everyday use.', 21.99, 27.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71CccB2qeFL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B01HXWT40E', 'chefsofi-mortar-and-pestle-set-6-inch-2-cup-capacity-un', 'Spice & Pantry Tools', 'spice-pantry-tools', 'SpiceVault', 'ChefSofi Mortar and Pestle Set', 'SpiceVault spice & pantry tools — authentic quality, carefully selected for everyday use.', 34.57, 43.21, 'IN_STOCK', 'https://m.media-amazon.com/images/I/91tu3+n-5CL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B07CHLML41', 'laevo-mortar-and-pestle-large-set-black-granite-stone-s', 'Spice & Pantry Tools', 'spice-pantry-tools', 'SpiceVault', 'Laevo Mortar and Pestle Large Set', 'SpiceVault spice & pantry tools — authentic quality, carefully selected for everyday use.', 22.41, 28.01, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81tec+LsBEL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B089W47KPC', 'tera-marble-mortar-and-pestle-set-small-bowl-solid-ston', 'Spice & Pantry Tools', 'spice-pantry-tools', 'SpiceVault', 'Tera Marble Mortar and Pestle Set Small Bowl Solid Stone Grinder …', 'SpiceVault spice & pantry tools — authentic quality, carefully selected for everyday use.', 17.99, 22.49, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71ODvMA86cS._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B009C5XMZO', 'antique-alive-antique-alive-mother-of-pearl-design-mone', 'Men''s Accessories', 'mens-accessories', 'VaultClip', 'Antique Alive Antique Alive Mother of Pearl Design Money Clip Sli…', 'VaultClip men''s accessories — authentic quality, carefully selected for everyday use.', 17.9, 22.38, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71T8xoDjtxL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B005SVBW7Q', 'm-clip-stainless-steel-money-clip-cash-and-credit-card-', 'Men''s Accessories', 'mens-accessories', 'VaultClip', 'M', 'VaultClip men''s accessories — authentic quality, carefully selected for everyday use.', 160, 200, 'IN_STOCK', 'https://m.media-amazon.com/images/I/616HdpqiqKL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B01N00RERR', 'lever-gear-toolcard-pro-with-money-clip-40-in-1-credit-', 'Men''s Accessories', 'mens-accessories', 'VaultClip', 'Lever Gear Toolcard Pro with Money Clip', 'VaultClip men''s accessories — authentic quality, carefully selected for everyday use.', 24.95, 31.19, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71cJSO3PPVL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0F2ZHBRGT', 'visworld-men-x27-s-wallet-with-airtag-holder-bifold-ful', 'Men''s Accessories', 'mens-accessories', 'VaultClip', 'VISWORLD Men&#x27;s Wallet with Airtag Holder', 'VaultClip men''s accessories — authentic quality, carefully selected for everyday use.', 23.99, 29.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/610kWkehtyL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FJF3SJPY', 'azurahide-zerofold-slim-credit-card-holder-men-x27-s-mi', 'Men''s Accessories', 'mens-accessories', 'VaultClip', 'AZURAHIDE ZeroFold Slim Credit Card Holder – Men&#x27;s Minimalis…', 'VaultClip men''s accessories — authentic quality, carefully selected for everyday use.', 13.99, 19, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61imOCFbCDL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B01GGG7PQS', 'serman-brands-rfid-blocking-wallet-slim-bifold-genuine-', 'Men''s Accessories', 'mens-accessories', 'VaultClip', 'SERMAN BRANDS RFID Blocking Wallet Slim Bifold', 'VaultClip men''s accessories — authentic quality, carefully selected for everyday use.', 24.99, 31.24, 'IN_STOCK', 'https://m.media-amazon.com/images/I/917tqhkaz-L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FBH2WR2V', '3-pcs-large-flower-bridal-wedding-hair-pins-crystal-pea', 'Women''s Accessories', 'womens-accessories', 'PearlLine', '3 PCS Large Flower Bridal Wedding Hair Pins Crystal Pearl Hair Cl…', 'PearlLine women''s accessories — authentic quality, carefully selected for everyday use.', 6.14, 8.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81iiIk8YjFL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DPM85FVJ', 'handmade-pearl-bridal-wedding-hair-pins-9pcs-white-flow', 'Women''s Accessories', 'womens-accessories', 'PearlLine', 'Handmade Pearl Bridal Wedding Hair Pins 9Pcs White Flower Pearls …', 'PearlLine women''s accessories — authentic quality, carefully selected for everyday use.', 18.99, 23.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/71-Ou25A+7L._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0FD9GJB6M', 'u-shaped-pearl-wedding-hair-pins-for-bridal-women-set-o', 'Women''s Accessories', 'womens-accessories', 'PearlLine', 'U Shaped Pearl Wedding Hair Pins for Bridal Women', 'PearlLine women''s accessories — authentic quality, carefully selected for everyday use.', 14.99, 18.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/61mNSXKztcL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0F7XMFHN6', 'muriersilk-100-mulberry-silk-scarf-for-women-for-neck-l', 'Women''s Accessories', 'womens-accessories', 'PearlLine', 'MurierSilk 100% Mulberry Silk Scarf for Women for Neck', 'PearlLine women''s accessories — authentic quality, carefully selected for everyday use.', 27.99, 34.99, 'IN_STOCK', 'https://m.media-amazon.com/images/I/81Ek9GT3aSL._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0DDPS1KCX', 'solanaluna-100-mulberry-silk-square-scarf-for-neck-or-h', 'Women''s Accessories', 'womens-accessories', 'PearlLine', 'Solanaluna 100% Mulberry Silk Square Scarf for Neck or Hair', 'PearlLine women''s accessories — authentic quality, carefully selected for everyday use.', 18.99, 23.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/9112qAKXUML._AC_UL960_QL65_.jpg');
INSERT INTO rapidapi_cache (id, slug, category, categorySlug, brand, title, description, basePrice, retailPrice, stockStatus, image_url) VALUES ('B0D6VFH9C6', 'cxzymcln-100-mulberry-silk-neck-scarf-21-quot-x21-quot-', 'Women''s Accessories', 'womens-accessories', 'PearlLine', 'cxzymcln 100% Mulberry Silk Neck Scarf 21&quot;x21&quot; Small Sq…', 'PearlLine women''s accessories — authentic quality, carefully selected for everyday use.', 14.99, 18.74, 'IN_STOCK', 'https://m.media-amazon.com/images/I/7155lSqN22L._AC_UL960_QL65_.jpg');
