<script lang="ts">
  import SessionManager from './SessionManager.svelte'; 

  let email = 'operator@symeno.com'; // Passed in production
  let twoFactorEnabled = $state(false);

  // 2FA Setup State
  let isSettingUp = $state(false);
  let setupUri = $state('');
  let setupSecret = $state('');
  let verificationCode = $state('');
  let isProcessing = $state(false);

  async function start2FASetup() {
    isProcessing = true;
    try {
      const res = await fetch('/api/account/2fa/setup', { method: 'POST' });
      if (res.ok) {
        const data = await res.json();
        setupUri = data.uri;
        setupSecret = data.secret;
        isSettingUp = true;
      }
    } finally {
      isProcessing = false;
    }
  }

  async function verifyAndEnable2FA() {
    isProcessing = true;
    try {
      const res = await fetch('/api/account/2fa/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: verificationCode }),
      });
      if (res.ok) {
        twoFactorEnabled = true;
        isSettingUp = false;
        alert('2FA Matrix Secured.');
      } else {
        const err = await res.json();
        alert(`Verification failed: ${err.error}`);     
      }
    } finally {
      isProcessing = false;
    }
  }
</script>

<div class="animate-fade-in space-y-12 transition-colors duration-300">
  <div
    class="grid grid-cols-1 gap-8 border-b border-outline pb-8 md:grid-cols-2"
  >
    <div>
      <h3
        class="mb-2 font-mono text-xs font-bold tracking-widest text-content uppercase"
      >
        Access Credentials
      </h3>
      <p class="mb-6 max-w-sm font-mono text-[10px] text-content-muted">
        Manage your primary authentication vectors.      
      </p>
      <div class="space-y-4">
        <div>
          <label
            class="mb-2 block font-mono text-[10px] font-bold tracking-widest text-content-muted uppercase"
            >Registered Email</label
          >
          <input
            type="email"
            value={email}
            disabled
            class="w-full border border-outline bg-base/50 px-3 py-2 font-mono text-sm text-content-muted"
          />
        </div>
      </div>
    </div>

    <div>
      <h3
        class="mb-2 font-mono text-xs font-bold tracking-widest text-content uppercase"
      >
        Multi-Factor Auth (TOTP)
      </h3>
      <p class="mb-6 max-w-sm font-mono text-[10px] text-content-muted">
        Secure your account using an authenticator app. 
      </p>

      {#if !isSettingUp}
        <div
          class="border p-4 {twoFactorEnabled
            ? 'border-brand/30 bg-brand/5'      
            : 'border-outline bg-base'} flex items-center justify-between transition-colors"
        >
          <div>
            <h4 class="mb-1 text-xs font-bold text-content">2FA Status</h4>
            <p
              class="font-mono text-[10px] {twoFactorEnabled
                ? 'text-brand'
                : 'text-content-muted'}"
            >
              {twoFactorEnabled ? 'Active & Enforced' : 'Currently Disabled'}
            </p>
          </div>
          <button
            onclick={start2FASetup}
            disabled={twoFactorEnabled || isProcessing} 
            class="{twoFactorEnabled
              ? 'hidden'
              : 'bg-brand text-brand-dark'} px-4 py-2 text-[10px] font-bold tracking-widest uppercase transition-colors hover:opacity-80 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand rounded-sm"
          >
            {isProcessing ? 'Initializing...' : 'Setup 2FA'}
          </button>
        </div>
      {:else}
        <div
          class="animate-fade-in space-y-4 border border-brand/50 bg-brand/5 p-4"
        >
          <h4
            class="text-xs font-bold tracking-widest text-brand uppercase"
          >
            Configuration Protocol
          </h4>
          <p class="font-mono text-[10px] text-content-muted">
            1. Enter this secret key into your Authenticator App (Google
            Authenticator, Authy):
          </p>
          <div
            class="border border-outline bg-base/50 p-2 text-center font-mono text-xs tracking-widest break-all text-content select-all"
          >
            {setupSecret}
          </div>
          <p class="mt-4 font-mono text-[10px] text-content-muted">
            2. Enter the 6-digit code generated by your app:
          </p>
          <div class="flex gap-2">
            <input
              type="text"
              bind:value={verificationCode}
              maxlength="6"
              placeholder="000000"
              class="w-full border border-outline bg-surface px-3 py-2 text-center font-mono text-lg tracking-[0.5em] text-content focus:border-brand/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand transition-colors"
            />
            <button
              onclick={verifyAndEnable2FA}
              disabled={verificationCode.length !== 6 || isProcessing}
              class="bg-brand px-6 text-[10px] font-bold tracking-widest text-brand-dark uppercase transition-colors hover:opacity-80 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand rounded-sm"
            >
              Verify
            </button>
          </div>
          <button
            onclick={() => (isSettingUp = false)}       
            class="mt-2 w-full font-mono text-[9px] tracking-widest text-content-muted uppercase transition-colors hover:text-content focus-visible:outline-none focus-visible:underline"
            >Cancel Setup</button
          >
        </div>
      {/if}
    </div>
  </div>
  <SessionManager />
</div>
