// Edge-native HTML generator for Resend (Zero Node.js dependency)
export function generateOrderReceiptHTML(order: any, items: any[]): string {
  const itemRows = items.map(i => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #333;">
        <p style="margin:0; font-weight: bold; color: #fff;">${i.title}</p>
        <p style="margin:0; font-size: 12px; color: #888;">SKU: ${i.sku}</p>
      </td>
      <td style="padding: 12px; border-bottom: 1px solid #333; text-align: center; color: #fff;">${i.quantity}</td>
      <td style="padding: 12px; border-bottom: 1px solid #333; text-align: right; color: #36f4a4;">$${(i.price * i.quantity).toFixed(2)}</td>
    </tr>
  `).join('');

  return `
    <div style="font-family: 'Courier New', Courier, monospace; color: #fff; background-color: #000; max-width: 600px; margin: 0 auto; border: 1px solid #333; padding: 30px;">
      <div style="border-bottom: 2px solid #36f4a4; padding-bottom: 20px; margin-bottom: 20px;">
        <h1 style="color: #36f4a4; font-size: 24px; text-transform: uppercase; margin: 0; letter-spacing: 2px;">Symeno Operations</h1>
        <p style="color: #888; font-size: 12px; margin-top: 5px;">Secure Transaction Receipt</p>
      </div>
      
      <div style="margin-bottom: 30px;">
        <p style="margin: 5px 0; font-size: 14px;"><strong>Order ID:</strong> ${order.id.toUpperCase()}</p>
        <p style="margin: 5px 0; font-size: 14px;"><strong>Status:</strong> ${order.status}</p>
      </div>

      <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
        <thead>
          <tr style="background-color: #111;">
            <th style="padding: 12px; text-align: left; font-size: 12px; color: #888; text-transform: uppercase;">Asset</th>
            <th style="padding: 12px; text-align: center; font-size: 12px; color: #888; text-transform: uppercase;">Qty</th>
            <th style="padding: 12px; text-align: right; font-size: 12px; color: #888; text-transform: uppercase;">Value</th>
          </tr>
        </thead>
        <tbody>
          ${itemRows}
        </tbody>
      </table>

      <div style="text-align: right; font-size: 18px; font-weight: bold; color: #36f4a4;">
        TOTAL: $${order.total.toFixed(2)}
      </div>

      <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #333; text-align: center; font-size: 10px; color: #555;">
        <p>This telemetry was automatically generated by the Symeno Logistics Engine.</p>
        <p>DO NOT REPLY TO THIS TRANSMISSION.</p>
      </div>
    </div>
  `;
}